// source: degreeCatalogCommand.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  (function () { return this; }).call(null) ||
  Function('return this')();

var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var result_pb = require('../../../result/protos/result_pb.js');
goog.object.extend(proto, result_pb);
goog.exportSymbol('proto.DegreeCatalog.AddDegreeCatalogRequest', null, global);
goog.exportSymbol('proto.DegreeCatalog.DeleteDegreeCatalogRequest', null, global);
goog.exportSymbol('proto.DegreeCatalog.UpdateDegreeCatalogRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DegreeCatalog.AddDegreeCatalogRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DegreeCatalog.AddDegreeCatalogRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DegreeCatalog.AddDegreeCatalogRequest.displayName = 'proto.DegreeCatalog.AddDegreeCatalogRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DegreeCatalog.UpdateDegreeCatalogRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DegreeCatalog.UpdateDegreeCatalogRequest.displayName = 'proto.DegreeCatalog.UpdateDegreeCatalogRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DegreeCatalog.DeleteDegreeCatalogRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DegreeCatalog.DeleteDegreeCatalogRequest.displayName = 'proto.DegreeCatalog.DeleteDegreeCatalogRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.DegreeCatalog.AddDegreeCatalogRequest.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.DegreeCatalog.AddDegreeCatalogRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.DegreeCatalog.AddDegreeCatalogRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
      degname: (f = msg.getDegname()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DegreeCatalog.AddDegreeCatalogRequest}
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DegreeCatalog.AddDegreeCatalogRequest;
  return proto.DegreeCatalog.AddDegreeCatalogRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DegreeCatalog.AddDegreeCatalogRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DegreeCatalog.AddDegreeCatalogRequest}
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new google_protobuf_wrappers_pb.StringValue;
        reader.readMessage(value, google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
        msg.setDegname(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.DegreeCatalog.AddDegreeCatalogRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DegreeCatalog.AddDegreeCatalogRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getDegname();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue DegName = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.getDegname = function () {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.DegreeCatalog.AddDegreeCatalogRequest} returns this
*/
proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.setDegname = function (value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DegreeCatalog.AddDegreeCatalogRequest} returns this
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.clearDegname = function () {
  return this.setDegname(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DegreeCatalog.AddDegreeCatalogRequest.prototype.hasDegname = function () {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.DegreeCatalog.UpdateDegreeCatalogRequest.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.DegreeCatalog.UpdateDegreeCatalogRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
      id: (f = msg.getId()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f),
      degname: (f = msg.getDegname()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DegreeCatalog.UpdateDegreeCatalogRequest;
  return proto.DegreeCatalog.UpdateDegreeCatalogRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new google_protobuf_wrappers_pb.Int32Value;
        reader.readMessage(value, google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
        msg.setId(value);
        break;
      case 2:
        var value = new google_protobuf_wrappers_pb.StringValue;
        reader.readMessage(value, google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
        msg.setDegname(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.DegreeCatalog.UpdateDegreeCatalogRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
  f = message.getDegname();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Int32Value Id = 1;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.getId = function () {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 1));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} returns this
*/
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.setId = function (value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} returns this
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.clearId = function () {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.hasId = function () {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue DegName = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.getDegname = function () {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} returns this
*/
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.setDegname = function (value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DegreeCatalog.UpdateDegreeCatalogRequest} returns this
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.clearDegname = function () {
  return this.setDegname(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DegreeCatalog.UpdateDegreeCatalogRequest.prototype.hasDegname = function () {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.DegreeCatalog.DeleteDegreeCatalogRequest.toObject(opt_includeInstance, this);
  };


  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.DegreeCatalog.DeleteDegreeCatalogRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.DegreeCatalog.DeleteDegreeCatalogRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
      id: (f = msg.getId()) && google_protobuf_wrappers_pb.Int32Value.toObject(includeInstance, f)
    };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DegreeCatalog.DeleteDegreeCatalogRequest}
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DegreeCatalog.DeleteDegreeCatalogRequest;
  return proto.DegreeCatalog.DeleteDegreeCatalogRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DegreeCatalog.DeleteDegreeCatalogRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DegreeCatalog.DeleteDegreeCatalogRequest}
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new google_protobuf_wrappers_pb.Int32Value;
        reader.readMessage(value, google_protobuf_wrappers_pb.Int32Value.deserializeBinaryFromReader);
        msg.setId(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.DegreeCatalog.DeleteDegreeCatalogRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DegreeCatalog.DeleteDegreeCatalogRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.Int32Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Int32Value Id = 1;
 * @return {?proto.google.protobuf.Int32Value}
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.getId = function () {
  return /** @type{?proto.google.protobuf.Int32Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.Int32Value, 1));
};


/**
 * @param {?proto.google.protobuf.Int32Value|undefined} value
 * @return {!proto.DegreeCatalog.DeleteDegreeCatalogRequest} returns this
*/
proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.setId = function (value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DegreeCatalog.DeleteDegreeCatalogRequest} returns this
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.clearId = function () {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DegreeCatalog.DeleteDegreeCatalogRequest.prototype.hasId = function () {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.DegreeCatalog);
