/**
 * @fileoverview gRPC-Web generated client stub for DegreeCatalog
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: degreeCatalogCommand.proto

/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as result_pb from '../../../result/protos/result_pb'; // proto import: "result.proto"
import * as degreeCatalogCommand_pb from './degreeCatalogCommand_pb'; // proto import: "degreeCatalogCommand.proto"


export class DegreeCatalogServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor(hostname: string,
    credentials?: null | { [index: string]: string; },
    options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorAddDegreeCatalog = new grpcWeb.MethodDescriptor(
    '/DegreeCatalog.DegreeCatalogService/AddDegreeCatalog',
    grpcWeb.MethodType.UNARY,
    degreeCatalogCommand_pb.AddDegreeCatalogRequest,
    result_pb.CommonResult,
    (request: degreeCatalogCommand_pb.AddDegreeCatalogRequest) => {
      return request.serializeBinary();
    },
    result_pb.CommonResult.deserializeBinary
  );

  addDegreeCatalog(
    request: degreeCatalogCommand_pb.AddDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null): Promise<result_pb.CommonResult>;

  addDegreeCatalog(
    request: degreeCatalogCommand_pb.AddDegreeCatalogRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void): grpcWeb.ClientReadableStream<result_pb.CommonResult>;

  addDegreeCatalog(
    request: degreeCatalogCommand_pb.AddDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
        '/DegreeCatalog.DegreeCatalogService/AddDegreeCatalog',
        request,
        metadata || {},
        this.methodDescriptorAddDegreeCatalog,
        callback);
    }
    return this.client_.unaryCall(
      this.hostname_ +
      '/DegreeCatalog.DegreeCatalogService/AddDegreeCatalog',
      request,
      metadata || {},
      this.methodDescriptorAddDegreeCatalog);
  }

  methodDescriptorUpdateDegreeCatalog = new grpcWeb.MethodDescriptor(
    '/DegreeCatalog.DegreeCatalogService/UpdateDegreeCatalog',
    grpcWeb.MethodType.UNARY,
    degreeCatalogCommand_pb.UpdateDegreeCatalogRequest,
    result_pb.CommonResult,
    (request: degreeCatalogCommand_pb.UpdateDegreeCatalogRequest) => {
      return request.serializeBinary();
    },
    result_pb.CommonResult.deserializeBinary
  );

  updateDegreeCatalog(
    request: degreeCatalogCommand_pb.UpdateDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null): Promise<result_pb.CommonResult>;

  updateDegreeCatalog(
    request: degreeCatalogCommand_pb.UpdateDegreeCatalogRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void): grpcWeb.ClientReadableStream<result_pb.CommonResult>;

  updateDegreeCatalog(
    request: degreeCatalogCommand_pb.UpdateDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
        '/DegreeCatalog.DegreeCatalogService/UpdateDegreeCatalog',
        request,
        metadata || {},
        this.methodDescriptorUpdateDegreeCatalog,
        callback);
    }
    return this.client_.unaryCall(
      this.hostname_ +
      '/DegreeCatalog.DegreeCatalogService/UpdateDegreeCatalog',
      request,
      metadata || {},
      this.methodDescriptorUpdateDegreeCatalog);
  }

  methodDescriptorDeleteDegreeCatalog = new grpcWeb.MethodDescriptor(
    '/DegreeCatalog.DegreeCatalogService/DeleteDegreeCatalog',
    grpcWeb.MethodType.UNARY,
    degreeCatalogCommand_pb.DeleteDegreeCatalogRequest,
    result_pb.CommonResult,
    (request: degreeCatalogCommand_pb.DeleteDegreeCatalogRequest) => {
      return request.serializeBinary();
    },
    result_pb.CommonResult.deserializeBinary
  );

  deleteDegreeCatalog(
    request: degreeCatalogCommand_pb.DeleteDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null): Promise<result_pb.CommonResult>;

  deleteDegreeCatalog(
    request: degreeCatalogCommand_pb.DeleteDegreeCatalogRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void): grpcWeb.ClientReadableStream<result_pb.CommonResult>;

  deleteDegreeCatalog(
    request: degreeCatalogCommand_pb.DeleteDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
        '/DegreeCatalog.DegreeCatalogService/DeleteDegreeCatalog',
        request,
        metadata || {},
        this.methodDescriptorDeleteDegreeCatalog,
        callback);
    }
    return this.client_.unaryCall(
      this.hostname_ +
      '/DegreeCatalog.DegreeCatalogService/DeleteDegreeCatalog',
      request,
      metadata || {},
      this.methodDescriptorDeleteDegreeCatalog);
  }

}

