/**
 * @fileoverview gRPC-Web generated client stub for DegreeCatalog
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: degreeCatalogQuery.proto

/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';
import * as result_pb from '../../../result/protos/result_pb'; // proto import: "result.proto"
import * as degreeCatalogQuery_pb from './degreeCatalogQuery_pb'; // proto import: "degreeCatalogQuery.proto"


export class DegreeCatalogServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor(hostname: string,
    credentials?: null | { [index: string]: string; },
    options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetDegreeCatalog = new grpcWeb.MethodDescriptor(
    '/DegreeCatalog.DegreeCatalogService/GetDegreeCatalog',
    grpcWeb.MethodType.UNARY,
    degreeCatalogQuery_pb.GetDegreeCatalogRequest,
    result_pb.CommonResult,
    (request: degreeCatalogQuery_pb.GetDegreeCatalogRequest) => {
      return request.serializeBinary();
    },
    result_pb.CommonResult.deserializeBinary
  );

  getDegreeCatalog(
    request: degreeCatalogQuery_pb.GetDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null): Promise<result_pb.CommonResult>;

  getDegreeCatalog(
    request: degreeCatalogQuery_pb.GetDegreeCatalogRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void): grpcWeb.ClientReadableStream<result_pb.CommonResult>;

  getDegreeCatalog(
    request: degreeCatalogQuery_pb.GetDegreeCatalogRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
        '/DegreeCatalog.DegreeCatalogService/GetDegreeCatalog',
        request,
        metadata || {},
        this.methodDescriptorGetDegreeCatalog,
        callback);
    }
    return this.client_.unaryCall(
      this.hostname_ +
      '/DegreeCatalog.DegreeCatalogService/GetDegreeCatalog',
      request,
      metadata || {},
      this.methodDescriptorGetDegreeCatalog);
  }

  methodDescriptorGetAllDegreeCatalogs = new grpcWeb.MethodDescriptor(
    '/DegreeCatalog.DegreeCatalogService/GetAllDegreeCatalogs',
    grpcWeb.MethodType.UNARY,
    degreeCatalogQuery_pb.GetAllDegreeCatalogsRequest,
    result_pb.CommonResult,
    (request: degreeCatalogQuery_pb.GetAllDegreeCatalogsRequest) => {
      return request.serializeBinary();
    },
    result_pb.CommonResult.deserializeBinary
  );

  getAllDegreeCatalogs(
    request: degreeCatalogQuery_pb.GetAllDegreeCatalogsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<result_pb.CommonResult>;

  getAllDegreeCatalogs(
    request: degreeCatalogQuery_pb.GetAllDegreeCatalogsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void): grpcWeb.ClientReadableStream<result_pb.CommonResult>;

  getAllDegreeCatalogs(
    request: degreeCatalogQuery_pb.GetAllDegreeCatalogsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
      response: result_pb.CommonResult) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
        '/DegreeCatalog.DegreeCatalogService/GetAllDegreeCatalogs',
        request,
        metadata || {},
        this.methodDescriptorGetAllDegreeCatalogs,
        callback);
    }
    return this.client_.unaryCall(
      this.hostname_ +
      '/DegreeCatalog.DegreeCatalogService/GetAllDegreeCatalogs',
      request,
      metadata || {},
      this.methodDescriptorGetAllDegreeCatalogs);
  }

}

